link_tutorial: https://www.railstutorial.org
link_help: https://www.railstutorial.org/help
link_book: https://www.railstutorial.org/book
link_screen: http://screencasts.railstutorial.org/
link_author: http://www.michaelhartl.com/
uses:
  name:
    maximum: 20
  email:
    maximum: 255
    valid: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  password:
    minimum: 6


